# Use root/example as user/password credentials
version: '3'
services:
   mariadb:
      image: mariadb
      volumes:
         - ~/data/maria:/var/lib/mysql
      restart: always
      environment:
         DBASE_LOGIN: "${DBASE_LOGIN}"
         DBASE_PSWD: "${DBASE_PSWD}"
      ports: 
            - "3306:3306"
      build:
         context: ./requirements/mariadb
         dockerfile: Dockerfile 
      networks:
         vpcbr:
      env_file: .env

   nginx:
      image: nginx
      restart: always
      depends_on:
         - wordpress
      ports:
            - "443:443"
      volumes:
            - ~/data/wp:/var/www/wordpress
      build:
         context: ./requirements/nginx
         dockerfile: Dockerfile
      networks:
         vpcbr:
      extra_hosts:
         - "mlizzie.42.fr:127.0.0.1"
      env_file: .env
   wordpress:
      image: wordpress:inc
      depends_on:
         - mariadb
      volumes:
         - ~/data/wp:/var/www/wordpress
      restart: always
      environment:
         WP_USER1_LOGIN: "${WP_USER1_LOGIN}"
         WP_USER1_PSWD: "${WP_USER1_PSWD}"
         WP_USER2_LOGIN: "${WP_USER2_LOGIN}"
         WP_USER2_PSWD: "${WP_USER2_PSWD}"
         DBASE_LOGIN: "${DBASE_LOGIN}"
         DBASE_PSWD: "${DBASE_PSWD}"
      ports:
         - "9000:9000"
      build:
         context: ./requirements/wordpress
         dockerfile: Dockerfile
      networks:
         vpcbr:
      env_file: .env         
networks:
    vpcbr:
        driver: bridge