version: "3.5"

services:
  mariadb:
    container_name: mariadb
    env_file: .env
    restart: always
    networks:
      - inception
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb_volume:/var/lib/mysql
    ports:
      - 3306:3306
  nginx:
    container_name: nginx
    env_file: .env
    restart: always
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    env_file: .env
    restart: always
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mariadb

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/imora/data/db
  wordpress_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/imora/data/wordpress

networks:
  inception:
    driver: bridge
