cat << EOF > /scripts/script.sql
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'gmother'@'%' IDENTIFIED BY 'JoJi003';
CREATE DATABASE IF NOT EXISTS ${DB_NAME} DEFAULT CHARACTER SET utf8;
GRANT ALL ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
UPDATE mysql.user SET PASSWORD = PASSWORD('${DB_ROOT_PASSWORD}') WHERE user = 'root';
UPDATE mysql.user SET PLUGIN = '' WHERE USER = 'root';
FLUSH PRIVILEGES;
EOF
sleep 1
mysqld_safe --init-file=/scripts/script.sql
